### ISSUE TITLE
Darzalib error, link expired

### ISSUE THREAD

**Issue by Slushiis** [swrlly/Midnight#3]
could you update the darzalib download?

**Comment by swrlly** [comment]
I decided to private the repository; it will not be available.

**Comment by Slushiis** [comment]
Oh, thank you for responding, is there any way to get the cheat tho, or
could you perhaps help me with an error that i get?
~,,
 Traceback (most recent call last):
  File "C:\Users\ssusi\Desktop\Midnight-main\Proxy.py", line 67, in <module>
    main()
  File "C:\Users\ssusi\Desktop\Midnight-main\Proxy.py", line 49, in main
    with open("data/ProjectileDictionary.pkl", "rb") as f: projDict =
pickle.load(f)
FileNotFoundError: [Errno 2] No such file or directory:
'data/ProjectileDictionary.pkl'
"
Please, reach out via discord,( Dreamas#2975 ) I'd like to talk a little
more
Have a nice day, Slushiis
